import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  th: {
    translation: {
      nav: { events: "อีเวนต์", promo: "โปรโมชัน", reviews: "รีวิว", home: "หน้าหลัก", festival: "เทศกาล", concert: "คอนเสิร์ต", exhibition: "นิทรรศการ", event: "อีเว้นท์" },
      header: { myTickets: "ตั๋วของฉัน", dashboard: "แดชบอร์ด", payment: "จ่ายเงิน", login: "เข้าสู่ระบบ", logout: "ออกจากระบบ", search: "ค้นหา", searchFull: "ค้นหาอีเวนต์ เทศกาล คอนเสิร์ต หรือปลายทาง...", searchBtn: "ค้นหา" },
      hero: { badge: "อีเวนต์แนะนำ", buy: "ซื้อบัตร", from: "เริ่ม" },
      home: { picks: "EventX เลือกให้", picksSub: "อีเวนต์แนะนำที่คนจองมากที่สุด", results: "ผลการค้นหา", upcoming: "อีเวนต์ที่กำลังจะมาถึง", upcomingSub: "จองล่วงหน้าก่อนบัตรหมด", destinations: "ปลายทางยอดนิยม", destinationsSub: "เลือกจังหวัดที่อยากไป", seeAll: "ดูทั้งหมด", events: "อีเวนต์", comingSoon: "จัดขึ้นเร็วๆนี้", allEvents: "งานทั้งหมด", searchPh: "ค้นหาอีเว้นท์ บัตร ศิลปิน หรืออื่นๆ....", popular: "คำค้นหายอดนิยมช่วงนี้ :", thisYear: "ปีนี้", tagLoy: "ลอยกระทง", tagLantern: "ปล่อยโคม", tagCountdown: "เคาท์ดาวน์" },
      cat: { all: "ทั้งหมด", festival: "เทศกาลแสงสี", concert: "คอนเสิร์ต", workshop: "เวิร์กช็อป", exhibition: "นิทรรศการ", outdoor: "กลางแจ้ง" },
      sort: { all: "ทั้งหมด", soon: "เร็ว ๆ นี้" },
      card: { onSale: "เปิดจำหน่าย", soon: "เร็ว ๆ นี้", full: "บัตรเต็ม", from: "เริ่มต้น", soldOutOverlay: "บัตรเต็มแล้ว", events: "อีเวนต์", reviews: "รีวิว" },
      detail: { home: "หน้าแรก", about: "เกี่ยวกับงาน", highlights: "ไฮไลท์ของงาน", gallery: "บรรยากาศภายในงาน", sessions: "รอบการแสดง", faq: "คำถามที่พบบ่อย", terms: "ข้อกำหนด", buyBarFrom: "เริ่มต้น", startPrice: "ราคาเริ่มต้น", buy: "ซื้อบัตร", buyNow: "ซื้อบัตรเลย", pickTitle: "เลือกบัตร", pickDate: "เลือกวันที่จอง", total: "รวม", unit: "ใบ", proceed: "ดำเนินการต่อ", loginToBook: "เข้าสู่ระบบเพื่อจอง", pickAtLeast: "เลือกบัตรอย่างน้อย 1 ใบ", soldOut: "บัตรเต็มแล้ว", notFound: "ไม่พบอีเวนต์ที่คุณค้นหา", backHome: "← กลับหน้าแรก" },
      checkout: {
        stepInfo: "ข้อมูลผู้จอง", stepPay: "ชำระเงิน", stepReceive: "รับบัตร",
        emptyCart: "ยังไม่มีบัตรในตะกร้า", chooseEvent: "เลือกอีเวนต์",
        formTitle: "ข้อมูลผู้จอง", formSub: "บัตร QR จะถูกส่งไปยังอีเมลนี้",
        title: "คำนำหน้า", mr: "นาย", mrs: "นาง", ms: "นางสาว", first: "ชื่อ", last: "นามสกุล", phone: "เบอร์โทร", email: "อีเมล",
        consent: "ฉันยอมรับ", privacy: "นโยบายความเป็นส่วนตัว", consentTail: "และยินยอมให้ EventX เก็บข้อมูลเพื่อการออกบัตร",
        validation: "กรุณากรอกข้อมูลให้ครบถ้วน (ชื่อ–สกุล เบอร์ 10 หลัก อีเมลถูกต้อง) และยอมรับนโยบายความเป็นส่วนตัว",
        proceedPay: "ดำเนินการชำระเงิน", summary: "สรุปคำสั่งซื้อ", total: "รวม", unit: "ใบ", via: "ผ่านลิงก์แนะนำ",
        payTitle: "สแกนเพื่อชำระเงิน", order: "ออเดอร์", payWithin: "ชำระภายใน", demoNote: "โหมดทดลอง — กดปุ่มด้านล่างเพื่อจำลองการชำระสำเร็จ",
        paySuccess: "จำลองชำระเงินสำเร็จ", issuing: "กำลังออกบัตร...", back: "ย้อนกลับ", holdNote: "ระบบจองที่นั่งไว้ให้ชั่วคราว หากไม่ชำระภายในเวลา ที่นั่งจะถูกปล่อยคืนอัตโนมัติ",
        expiredTitle: "หมดเวลาการจอง", expiredBody: "หมดเวลาชำระเงิน ที่นั่งถูกปล่อยคืนเข้าระบบแล้ว", restart: "เริ่มจองใหม่", home: "กลับหน้าแรก",
        successTitle: "ชำระเงินสำเร็จ", successBody: "บัตร QR ถูกส่งไปยังอีเมล",
      },
      tickets: { title: "ตั๋วของฉัน", sub: "บัตร QR ทั้งหมดที่คุณซื้อ ใช้แสดงที่จุดสแกนหน้างาน", empty: "ยังไม่มีบัตร", emptySub: "เลือกอีเวนต์แล้วซื้อบัตรเพื่อเริ่มใช้งาน", choose: "เลือกอีเวนต์", ready: "พร้อมใช้งาน", used: "เช็คอินแล้ว", order: "ออเดอร์", downloadPdf: "ดาวน์โหลด PDF", loading: "กำลังโหลดบัตร…" },
      login: { title: "เข้าสู่ระบบ / สมัครสมาชิก", signup: "สมัครสมาชิก", subtitle: "เบอร์โทรศัพท์ไทยเท่านั้น", phone: "หมายเลขโทรศัพท์", otp: "ขอรหัส OTP", or: "หรือ", google: "ดำเนินการต่อด้วย Google", email: "ดำเนินการต่อด้วย email", help: "หากมีปัญหาการเข้าใช้งาน", contact: "ติดต่อฝ่ายบริการลูกค้า", tabLogin: "เข้าสู่ระบบ", tabRegister: "สมัครสมาชิก", otpTitle: "กรอกรหัส OTP", otpSentTo: "ส่งรหัส 6 หลักไปที่", otpHint: "โหมดทดลอง — กรอกเลข 6 หลักใดก็ได้ (เช่น 123456)", verify: "ยืนยันรหัส", back: "← เปลี่ยนเบอร์", resend: "ส่งรหัสอีกครั้ง", name: "ชื่อ–นามสกุล", emailLabel: "อีเมล", regBtn: "สมัครและเข้าสู่ระบบ", regValidation: "กรอกชื่อ เบอร์ 10 หลัก และอีเมลให้ถูกต้อง", logout: "ออกจากระบบ", greeting: "สวัสดี", pleaseWait: "กำลังดำเนินการ…", loginFailed: "เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่", registerFailed: "สมัครสมาชิกไม่สำเร็จ กรุณาลองใหม่" },
      portal: { title: "เข้าสู่ {{role}}", sub: "โหมดทดลอง — กดเพื่อเข้าใช้งานพอร์ทัลนี้", loginFirst: "เข้าสู่ระบบก่อน", enter: "เข้าสู่โหมด {{role}}", note: "เดโม: ระบบจริงจะกำหนดสิทธิ์ผ่านการอนุมัติ/ผู้ให้บริการยืนยันตัวตน", failed: "เข้าโหมดไม่สำเร็จ" },
      footer: { platformTagline: "แพลตฟอร์มจำหน่ายบัตรเข้าชมงานอีเวนต์และคอนเสิร์ตชั้นนำ", tagline: "EventX — แพลตฟอร์มจัดจำหน่ายอีเวนต์และการท่องเที่ยว", about: "เกี่ยวกับเรา", privacy: "นโยบายความเป็นส่วนตัว", terms: "ข้อกำหนดการใช้งาน", forOrganizer: "สำหรับผู้จัดงาน", agentPortal: "พอร์ทัลตัวแทน", affiliatePortal: "พอร์ทัล Affiliate", admin: "ผู้ดูแลระบบ", contact: "ติดต่อเรา", cookies: "คุกกี้", rights: "© 2026 EventX. สงวนลิขสิทธิ์", supports: "รองรับ" },
      agent: { dash: "แดชบอร์ด", book: "สร้างการจอง", dashTitle: "แดชบอร์ดตัวแทน", dashSub: "ออกบัตรแทนลูกค้า — รับเงินสด/เคลียร์ยอดกับผู้จัดงานเอง", newBooking: "+ สร้างการจอง", sBookings: "การจองทั้งหมด", tickets: "ใบ", sCustomers: "ลูกค้า", people: "ราย", sOutstanding: "ยอดค้างชำระกับผู้จัด", outHint: "เคลียร์กับผู้จัดงานเอง", recent: "การจองล่าสุด", empty: "ยังไม่มีการจอง", emptySub: "เริ่มออกบัตรให้ลูกค้าได้เลย", first: "สร้างการจองแรก", colNo: "เลขที่", colEvent: "อีเวนต์ / ลูกค้า", colTicket: "บัตร", colAmount: "ยอด", colStatus: "สถานะ", bookTitle: "สร้างการจอง", bookSub: "ออกบัตรแทนลูกค้า — ออกได้ทันที ไม่ต้องชำระผ่านระบบ", step1: "1. เลือกอีเวนต์", selectEvent: "— เลือกอีเวนต์ —", step2: "2. เลือกบัตร", session: "รอบการแสดง", ticketType: "ประเภทบัตร", qty: "จำนวน", step3: "3. ข้อมูลลูกค้า", summary: "สรุปการจอง", agentLabel: "ตัวแทน", eventLabel: "อีเวนต์", ticketLabel: "บัตร", receiveAmt: "ยอดรับจากลูกค้า", cashNote: "เก็บเงินสดจากลูกค้า แล้วเคลียร์กับผู้จัดงานเอง", issue: "ออกบัตร", issuing: "กำลังออกบัตร...", successTitle: "ออกบัตรสำเร็จ", successSub: "ส่งบัตรจริงให้ลูกค้าที่", andCopy: "+ สำเนาให้ตัวแทนแล้ว", custTickets: "บัตรลูกค้า", agentCopy: "สำเนาตัวแทน", agentCopyName: "สำเนาสำหรับตัวแทน", issueNew: "ออกบัตรใบใหม่", toDash: "ไปแดชบอร์ด" },
      admin: { dash: "แดชบอร์ด", events: "อีเวนต์", organizers: "ผู้จัดงาน", users: "ผู้ใช้", role: "ผู้ดูแลระบบ", dashTitle: "แดชบอร์ดผู้ดูแลระบบ", dashSub: "ภาพรวมแพลตฟอร์ม — จัดการอีเวนต์ที่ลงเอง และอนุมัติผู้จัดงานพาร์ทเนอร์", sGmv: "GMV (ประมาณการ)", sEvents: "อีเวนต์ทั้งหมด", sPartners: "ผู้จัดงาน (อนุมัติแล้ว)", sPending: "ใบสมัครรออนุมัติ", needReview: "ต้องตรวจ", manageEvents: "จัดการอีเวนต์", manageEventsSub: "สร้าง/เผยแพร่อีเวนต์ที่ EventX ลงเอง (INTERNAL)", orgCard: "ผู้จัดงาน (พาร์ทเนอร์)", orgCardSub: "อนุมัติใบสมัคร + ตั้งค่าดำเนินการ %", reviewBadge: "รอตรวจ", evTitle: "อีเวนต์ (INTERNAL)", evSub: "อีเวนต์ที่ EventX จัดหามาลงเอง — ดูแลในหน้านี้", createEvent: "+ สร้างอีเวนต์", closeForm: "ปิดฟอร์ม", newEvent: "สร้างอีเวนต์ใหม่", fName: "ชื่ออีเวนต์", fProvince: "จังหวัด", fCategory: "หมวดหมู่", fDate: "วันที่ (ข้อความ)", fPrice: "ราคาเริ่มต้น (บาท)", saveDraft: "บันทึก (แบบร่าง)", colEvent: "อีเวนต์", colCat: "หมวด/จังหวัด", colDate: "วันที่", colFrom: "เริ่มต้น", colStatus: "สถานะ", published: "เผยแพร่", draftPublish: "แบบร่าง · เผยแพร่", orgTitle: "ผู้จัดงาน (พาร์ทเนอร์)", orgSub: "อนุมัติใบสมัคร แล้วตั้งค่าดำเนินการ (% ที่ EventX หัก) ก่อนเปิดให้ขาย", discussing: "กำลังคุย", approved: "อนุมัติแล้ว", rejected: "ปฏิเสธ", expectSell: "คาดว่าจะขาย", unit: "ใบ", fee: "ค่าดำเนินการ", feePct: "ค่าดำเนินการ (%)", approve: "อนุมัติ + ตั้ง fee", reject: "ปฏิเสธ" },
      organizer: { dash: "แดชบอร์ด", events: "งานของฉัน", feeLabel: "ค่าดำเนินการ", dashTitle: "แดชบอร์ดผู้จัดงาน", dashSub: "ภาพรวมยอดขายของงานคุณ — ยอดรับสุทธิคำนวณหลังหักค่าดำเนินการแล้ว", sGmv: "ยอดขายรวม (GMV)", sSold: "ตั๋วที่ขายแล้ว", events_: "อีเวนต์", sFee: "ค่าดำเนินการ EventX", sNet: "ยอดรับสุทธิ", myEvents: "งานของฉัน", seeAll: "ดูทั้งหมด", colEvent: "อีเวนต์", colDate: "วันที่", colSold: "ขาย/โควต้า", colRevenue: "ยอดขาย", colCheckin: "เช็คอิน", openScan: "เปิดหน้าสแกนเช็คอิน", evSub: "ติดตามยอดขายแต่ละงาน และเปิดสแกนเช็คอินหน้างาน", onSale: "เปิดขาย", revenue: "ยอดขาย", soldOf: "ขายแล้ว", scan: "สแกนเช็คอิน", viewPage: "ดูหน้างาน", exportExcel: "ส่งออกรายชื่อ (Excel)", perTicket: "ต่อใบ" },
      checkin: { portal: "CHECK-IN", checkedIn: "เช็คอินแล้ว", unit: "ใบ", successTitle: "เช็คอินสำเร็จ", usedTitle: "บัตรนี้ถูกใช้แล้ว", notFound: "ไม่พบบัตร / บัตรไม่ถูกต้อง", openCam: "เปิดกล้องเพื่อสแกน QR", orEnter: "หรือกรอกเลขบัตร / วางข้อมูล QR", check: "ตรวจ", recent: "สแกนล่าสุด", pass: "ผ่าน", used: "ใช้แล้ว", missing: "ไม่พบ", camErr: "เปิดกล้องไม่ได้ — ใช้การกรอกเลขบัตรแทนได้" },
      adminUsers: { title: "จัดการผู้ใช้", sub: "รายชื่อผู้ใช้ทุกบทบาท — คลิกเพื่อดูรายละเอียด", all: "ทั้งหมด", customer: "ลูกค้า", agent: "ตัวแทน", affiliate: "ตัวแทนแนะนำ", organizer: "ผู้จัดงาน", search: "ค้นหา ชื่อ/อีเมล/เบอร์", colUser: "ผู้ใช้", colRole: "บทบาท", colStatus: "สถานะ", active: "ใช้งาน", suspended: "ระงับ", notFound: "ไม่พบผู้ใช้", email: "อีเมล", phone: "เบอร์โทร", joined: "สมัครเมื่อ", orders: "ออเดอร์/การจอง", status: "สถานะ", note: "หมายเหตุ", suspend: "ระงับบัญชี", activate: "เปิดใช้งาน", selectUser: "เลือกผู้ใช้เพื่อดูรายละเอียด" },
      aff: { dash: "แดชบอร์ด", links: "ลิงก์แนะนำ", rateLabel: "คอมมิชชั่น", dashTitle: "แดชบอร์ดตัวแทนแนะนำ", dashSub: "แชร์ลิงก์ → ลูกค้าซื้อ → รับคอมมิชชั่น (จ่ายตอนรอบ settlement)", withdraw: "ขอถอนเงิน", sClicks: "คลิกทั้งหมด", sOrders: "ออเดอร์ที่ปิดได้", conversion: "Conversion", sRevenue: "ยอดขายที่แนะนำ", sPending: "คอมมิชชั่นรอจ่าย", totalEarned: "สะสมทั้งหมด", linksTitle: "ลิงก์แนะนำ", manageLinks: "จัดการลิงก์", colEventCode: "อีเวนต์ / โค้ด", colClicks: "คลิก", colOrders: "ออเดอร์", colRevenue: "ยอดขาย", commTitle: "คอมมิชชั่นล่าสุด", colOrder: "ออเดอร์", colEvent: "อีเวนต์", colComm: "คอมมิชชั่น", colStatus: "สถานะ", pending: "รอจ่าย", settled: "จ่ายแล้ว", referred: "ผู้ใช้ที่คุณแนะนำมา", colUser: "ผู้ใช้", colJoined: "สมัครเมื่อ", colSpent: "ใช้จ่าย", colYourComm: "คอมของคุณ", pdpaNote: "* อีเมลถูกปกปิดบางส่วนเพื่อความเป็นส่วนตัว (PDPA)", joinTitle: "เป็นตัวแทนแนะนำกับ EventX", joinSub: "แชร์ลิงก์อีเวนต์ที่คุณชอบ รับคอมมิชชั่น 10% จากทุกการขายที่ปิดได้ พร้อมดูข้อมูลผู้ใช้ที่คุณแนะนำมาในแดชบอร์ดเดียว", joinCta: "สมัครเป็นตัวแทนแนะนำ", applyTitle: "สมัครเป็นตัวแทนแนะนำ", applySub: "แชร์ลิงก์อีเวนต์ รับคอมมิชชั่น 10% จากทุกการขายที่ปิดได้ผ่านลิงก์ของคุณ", fName: "ชื่อ–นามสกุล / ชื่อเพจ", fEmail: "อีเมล", fPhone: "เบอร์โทร", fChannel: "ช่องทางที่ใช้โปรโมต", channelPh: "เช่น Instagram / TikTok / กลุ่ม Facebook", applyValidation: "กรุณากรอกข้อมูลให้ครบถ้วน (ชื่อ อีเมล เบอร์ 10 หลัก และช่องทางโปรโมต)", applyBtn: "สมัครและเริ่มใช้งาน", applyFree: "สมัครฟรี — เริ่มสร้างลิงก์และรับคอมมิชชั่นได้ทันที", linksPageTitle: "ลิงก์แนะนำของฉัน", linksPageSub: "คัดลอกลิงก์ไปแชร์ — เมื่อมีคนซื้อผ่านลิงก์ คุณจะได้รับคอมมิชชั่น", copy: "คัดลอก", copied: "คัดลอกแล้ว ✓" },
    },
  },
  en: {
    translation: {
      nav: { events: "Events", promo: "Promotions", reviews: "Reviews", home: "Home", festival: "Festivals", concert: "Concerts", exhibition: "Exhibitions", event: "Events" },
      header: { myTickets: "My Tickets", dashboard: "Dashboard", payment: "Payment", login: "Sign in", logout: "Sign out", search: "Search", searchFull: "Search events, festivals, concerts or destinations...", searchBtn: "Search" },
      hero: { badge: "Featured", buy: "Buy tickets", from: "From" },
      home: { picks: "EventX Picks", picksSub: "Top events booked by everyone", results: "Search results", upcoming: "Upcoming events", upcomingSub: "Book before they sell out", destinations: "Popular destinations", destinationsSub: "Pick where you want to go", seeAll: "See all", events: "Events", comingSoon: "Coming soon", allEvents: "All events", searchPh: "Search events, tickets, artists and more....", popular: "Popular searches:", thisYear: "This year", tagLoy: "Loy Krathong", tagLantern: "Sky lanterns", tagCountdown: "Countdown" },
      cat: { all: "All", festival: "Festival of Lights", concert: "Concerts", workshop: "Workshops", exhibition: "Exhibitions", outdoor: "Outdoor" },
      sort: { all: "All", soon: "Coming soon" },
      card: { onSale: "On sale", soon: "Coming soon", full: "Sold out", from: "From", soldOutOverlay: "Sold out", events: "Events", reviews: "reviews" },
      detail: { home: "Home", about: "About", highlights: "Event highlights", gallery: "Event gallery", sessions: "Sessions", faq: "FAQ", terms: "Terms", buyBarFrom: "From", startPrice: "Starting price", buy: "Buy tickets", buyNow: "Buy tickets", pickTitle: "Select tickets", pickDate: "Select date", total: "Total", unit: "tickets", proceed: "Continue", loginToBook: "Sign in to book", pickAtLeast: "Select at least 1 ticket", soldOut: "Sold out", notFound: "Event not found", backHome: "← Back home" },
      checkout: {
        stepInfo: "Buyer info", stepPay: "Payment", stepReceive: "Tickets",
        emptyCart: "Your cart is empty", chooseEvent: "Choose an event",
        formTitle: "Buyer information", formSub: "QR tickets will be sent to this email",
        title: "Title", mr: "Mr.", mrs: "Mrs.", ms: "Ms.", first: "First name", last: "Last name", phone: "Phone", email: "Email",
        consent: "I accept the", privacy: "Privacy Policy", consentTail: "and consent to EventX storing my data to issue tickets",
        validation: "Please complete all fields (name, 10-digit phone, valid email) and accept the privacy policy",
        proceedPay: "Proceed to payment", summary: "Order summary", total: "Total", unit: "tickets", via: "via referral",
        payTitle: "Scan to pay", order: "Order", payWithin: "Pay within", demoNote: "Demo mode — tap below to simulate a successful payment",
        paySuccess: "Simulate successful payment", issuing: "Issuing tickets...", back: "Back", holdNote: "Seats are held temporarily. If unpaid in time, they are released automatically.",
        expiredTitle: "Booking expired", expiredBody: "Payment time ran out. Seats have been released.", restart: "Book again", home: "Back home",
        successTitle: "Payment successful", successBody: "QR tickets sent to",
      },
      tickets: { title: "My Tickets", sub: "All QR tickets you bought — show them at the gate scanner", empty: "No tickets yet", emptySub: "Pick an event and buy a ticket to get started", choose: "Browse events", ready: "Ready", used: "Checked in", order: "Order", downloadPdf: "Download PDF", loading: "Loading tickets…" },
      login: { title: "Sign in / Sign up", signup: "Sign up", subtitle: "Thai phone numbers only", phone: "Phone number", otp: "Request OTP", or: "or", google: "Continue with Google", email: "Continue with email", help: "Having trouble?", contact: "Contact support", tabLogin: "Sign in", tabRegister: "Sign up", otpTitle: "Enter OTP", otpSentTo: "6-digit code sent to", otpHint: "Demo mode — enter any 6 digits (e.g. 123456)", verify: "Verify code", back: "← Change number", resend: "Resend code", name: "Full name", emailLabel: "Email", regBtn: "Sign up & continue", regValidation: "Enter name, 10-digit phone, and a valid email", logout: "Sign out", greeting: "Hi", pleaseWait: "Please wait…", loginFailed: "Sign in failed. Please try again", registerFailed: "Sign up failed. Please try again" },
      portal: { title: "Enter {{role}}", sub: "Demo mode — tap to access this portal", loginFirst: "Sign in first", enter: "Enter {{role}} mode", note: "Demo: production assigns roles via approval / identity provider", failed: "Could not enter mode" },
      footer: { platformTagline: "The leading platform for event & concert tickets", tagline: "EventX — event distribution & travel platform", about: "About us", privacy: "Privacy policy", terms: "Terms of use", forOrganizer: "For organizers", agentPortal: "Agent portal", affiliatePortal: "Affiliate portal", admin: "Admin", contact: "Contact", cookies: "Cookies", rights: "© 2026 EventX. All rights reserved.", supports: "We accept" },
      agent: { dash: "Dashboard", book: "New booking", dashTitle: "Agent dashboard", dashSub: "Issue tickets for customers — collect cash & settle with organizers yourself", newBooking: "+ New booking", sBookings: "Total bookings", tickets: "tickets", sCustomers: "Customers", people: "people", sOutstanding: "Outstanding to organizer", outHint: "settle with organizers yourself", recent: "Recent bookings", empty: "No bookings yet", emptySub: "Start issuing tickets for customers", first: "Create first booking", colNo: "No.", colEvent: "Event / Customer", colTicket: "Ticket", colAmount: "Amount", colStatus: "Status", bookTitle: "New booking", bookSub: "Issue tickets for customers — instant, no online payment needed", step1: "1. Select event", selectEvent: "— Select an event —", step2: "2. Select tickets", session: "Session", ticketType: "Ticket type", qty: "Quantity", step3: "3. Customer info", summary: "Booking summary", agentLabel: "Agent", eventLabel: "Event", ticketLabel: "Ticket", receiveAmt: "Collect from customer", cashNote: "Collect cash from the customer, then settle with the organizer", issue: "Issue tickets", issuing: "Issuing...", successTitle: "Tickets issued", successSub: "Sent the real ticket to the customer at", andCopy: "+ a copy to the agent", custTickets: "Customer tickets", agentCopy: "Agent copy", agentCopyName: "Copy for agent", issueNew: "Issue another", toDash: "Go to dashboard" },
      admin: { dash: "Dashboard", events: "Events", organizers: "Organizers", users: "Users", role: "Administrator", dashTitle: "Admin dashboard", dashSub: "Platform overview — manage internal events and approve partner organizers", sGmv: "GMV (est.)", sEvents: "Total events", sPartners: "Organizers (approved)", sPending: "Pending applications", needReview: "review needed", manageEvents: "Manage events", manageEventsSub: "Create/publish events EventX lists itself (INTERNAL)", orgCard: "Organizers (partners)", orgCardSub: "Approve applications + set processing fee %", reviewBadge: "to review", evTitle: "Events (INTERNAL)", evSub: "Events EventX sources and lists itself — managed here", createEvent: "+ Create event", closeForm: "Close form", newEvent: "Create new event", fName: "Event name", fProvince: "Province", fCategory: "Category", fDate: "Date (text)", fPrice: "Starting price (THB)", saveDraft: "Save (draft)", colEvent: "Event", colCat: "Category/Province", colDate: "Date", colFrom: "From", colStatus: "Status", published: "Published", draftPublish: "Draft · Publish", orgTitle: "Organizers (partners)", orgSub: "Approve applications, then set the processing fee (% EventX deducts) before going live", discussing: "In discussion", approved: "Approved", rejected: "Rejected", expectSell: "Expects to sell", unit: "tickets", fee: "Fee", feePct: "Processing fee (%)", approve: "Approve + set fee", reject: "Reject" },
      organizer: { dash: "Dashboard", events: "My events", feeLabel: "Fee", dashTitle: "Organizer dashboard", dashSub: "Sales overview for your events — net payout is after the processing fee", sGmv: "Total sales (GMV)", sSold: "Tickets sold", events_: "events", sFee: "EventX fee", sNet: "Net payout", myEvents: "My events", seeAll: "See all", colEvent: "Event", colDate: "Date", colSold: "Sold/Quota", colRevenue: "Sales", colCheckin: "Checked in", openScan: "Open check-in scanner", evSub: "Track sales per event and open the on-site check-in scanner", onSale: "On sale", revenue: "Sales", soldOf: "Sold", scan: "Scan check-in", viewPage: "View page", exportExcel: "Export list (Excel)", perTicket: "per ticket" },
      checkin: { portal: "CHECK-IN", checkedIn: "checked in", unit: "tickets", successTitle: "Check-in successful", usedTitle: "This ticket was already used", notFound: "Ticket not found / invalid", openCam: "Open camera to scan QR", orEnter: "Or enter ticket no. / paste QR data", check: "Check", recent: "Recent scans", pass: "OK", used: "Used", missing: "Not found", camErr: "Cannot open camera — use manual entry instead" },
      adminUsers: { title: "User management", sub: "All users across roles — click to view details", all: "All", customer: "Customer", agent: "Agent", affiliate: "Affiliate", organizer: "Organizer", search: "Search name/email/phone", colUser: "User", colRole: "Role", colStatus: "Status", active: "Active", suspended: "Suspended", notFound: "No users found", email: "Email", phone: "Phone", joined: "Joined", orders: "Orders/bookings", status: "Status", note: "Note", suspend: "Suspend account", activate: "Activate", selectUser: "Select a user to view details" },
      aff: { dash: "Dashboard", links: "Referral links", rateLabel: "Commission", dashTitle: "Affiliate dashboard", dashSub: "Share links → customers buy → earn commission (paid at settlement)", withdraw: "Withdraw", sClicks: "Total clicks", sOrders: "Orders closed", conversion: "Conversion", sRevenue: "Revenue referred", sPending: "Pending commission", totalEarned: "Total earned", linksTitle: "Referral links", manageLinks: "Manage links", colEventCode: "Event / Code", colClicks: "Clicks", colOrders: "Orders", colRevenue: "Revenue", commTitle: "Recent commissions", colOrder: "Order", colEvent: "Event", colComm: "Commission", colStatus: "Status", pending: "Pending", settled: "Settled", referred: "Users you referred", colUser: "User", colJoined: "Joined", colSpent: "Spent", colYourComm: "Your commission", pdpaNote: "* Emails partly masked for privacy (PDPA)", joinTitle: "Become an EventX affiliate", joinSub: "Share links to events you love and earn 10% commission on every sale, plus see who you referred — all in one dashboard", joinCta: "Become an affiliate", applyTitle: "Become an affiliate", applySub: "Share event links and earn 10% commission on every sale closed through your links", fName: "Full name / page name", fEmail: "Email", fPhone: "Phone", fChannel: "Promotion channel", channelPh: "e.g. Instagram / TikTok / Facebook group", applyValidation: "Please complete all fields (name, email, 10-digit phone, and channel)", applyBtn: "Sign up & get started", applyFree: "Free to join — create links and earn commission right away", linksPageTitle: "My referral links", linksPageSub: "Copy and share — earn commission when someone buys through your link", copy: "Copy", copied: "Copied ✓" },
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "th",
  fallbackLng: "th",
  interpolation: { escapeValue: false },
});

export default i18n;
